AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Description: 'Web Scrapping Test'

Metadata: {}

Parameters: 

    Name:
        Type: String
        Default: web-scrapping

    Project:
        Type: String
        Default: web-scrapping-crawler

    Environment:
        Type: String
        Default: dev

Mappings: {}

Conditions: {}

Resources:

    #
    # Tables
    #

    TableOutLinks:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: link
                  AttributeType: S
                - AttributeName: appearences
                  AttributeType: N    
            KeySchema:
                - AttributeName: link
                  KeyType: HASH
                - AttributeName: appearences
                  KeyType: RANGE
            BillingMode: PAY_PER_REQUEST

    #
    # Functions
    #
    
    ##### Crawler ####

    # Lambda Layer
    RuntimeDependenciesLayerCrawler:
        Type: AWS::Serverless::LayerVersion
        Metadata:
            BuildMethod: makefile
        Properties:
            Description: Runtime dependencies for Lambdas
            ContentUri: ../src/crawler_job
            CompatibleRuntimes:
                - python3.7
            RetentionPolicy: Delete

    # Lambda Function
    WebScrappingCrawler:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${Name}-crawler
            Handler: main.lambda_handler
            Runtime: python3.7
            CodeUri: ../src/crawler_job
            Description: Web Scrapping Lambda Crawler
            Timeout: 900
            MemorySize: 3072
            Layers:
                - !Ref RuntimeDependenciesLayerCrawler
            Tags:
                Name: !Sub ${Name}-crawler
                Project: !Ref Project
                Environment: !Ref Environment

    ##### API ####
