AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Description: 'Web Scrapping Test'

Metadata: {}

Parameters: 

    Name:
        Type: String
        Default: api-web-scrapping

    Project:
        Type: String
        Default: web-scrapping-crawler

    Environment:
        Type: String
        Default: dev

Mappings: {}

Conditions: {}

Resources:

    #
    # Tables
    #

    TableUrlCrawler:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: table-url-crawler
            AttributeDefinitions:
                - AttributeName: link
                  AttributeType: S
            KeySchema:
                - AttributeName: link
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST

    #
    # Functions
    #
    
    ##### API ####

    # Lambda Layer
    RuntimeDependenciesLayerAPICrawler:
        Type: AWS::Serverless::LayerVersion
        Metadata:
            BuildMethod: makefile
        Properties:
            Description: Runtime dependencies for Lambdas
            ContentUri: ../src/api
            CompatibleRuntimes:
                - python3.7
            RetentionPolicy: Delete

    # Lambda Function
    WebScrappingCrawler:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${Name}-api-crawler
            Handler: main.lambda_handler
            Runtime: python3.7
            CodeUri: ../src/api
            Description: API Web Scrapping Lambda Crawler
            Timeout: 900
            Policies: AmazonDynamoDBFullAccess
            Environment:
                Variables:
                    TABLE_NAME: !Ref TableUrlCrawler
            Layers:
                - !Ref RuntimeDependenciesLayerAPICrawler
            Tags:
                Name: !Sub ${Name}-api-crawler
                Project: !Ref Project
                Environment: !Ref Environment
            Events:
                Crawler:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /crawler
                        Method: get
                        RequestParameters:
                            - method.request.querystring.url:
                                Required: true

Outputs:

    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    CrawlerApi:
        Description: "API Gateway endpoint URL"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/crawler/"
    WebScrappingCrawler:
        Description: "WebScrappingCrawler Lambda Function ARN"
        Value: !GetAtt WebScrappingCrawler.Arn
    WebScrappingCrawlerIamRole:
        Description: "Implicit IAM Role created for WebScrappingCrawler function"
        Value: !GetAtt WebScrappingCrawlerRole.Arn