AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Description: 'Web Scrapping Test'

Metadata: {}

Parameters: 

    Name:
        Type: String
        Default: api-web-scrapping

    Project:
        Type: String
        Default: web-scrapping-crawler

    Environment:
        Type: String
        Default: dev

Mappings: {}

Conditions: {}

Resources:

    #
    # Tables
    #

    TableUrlCrawler:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: table-url-crawler
            AttributeDefinitions:
                - AttributeName: link
                  AttributeType: S
            KeySchema:
                - AttributeName: link
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST

    #
    # Functions
    #
    
    ##### API ####

    # Lambda Layer
    RuntimeDependenciesLayerAPICrawler:
        Type: AWS::Serverless::LayerVersion
        Metadata:
            BuildMethod: makefile
        Properties:
            Description: Runtime dependencies for Lambdas
            ContentUri: ../src/api
            CompatibleRuntimes:
                - python3.7
            RetentionPolicy: Delete

    # Lambda Function
    WebScrappingCrawler:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${Name}-api-crawler
            Handler: main.lambda_handler
            Runtime: python3.7
            CodeUri: ../src/api
            Description: API Web Scrapping Lambda Crawler
            Timeout: 900
            Policies: AmazonDynamoDBFullAccess
            Environment:
                Variables:
                    TABLE_NAME: !Ref TableUrlCrawler
            Layers:
                - !Ref RuntimeDependenciesLayerAPICrawler
            Tags:
                Name: !Sub ${Name}-api-crawler
                Project: !Ref Project
                Environment: !Ref Environment