{"link": "https://scrapethissite.com/", "appearences": 0}
{"link": "http://www.example.com/", "appearences": 0}
{"link": "https://scrapethissite.com/", "appearences": 0}
{"link": "https://scrapethissite.com/pages/", "appearences": 0}
{"link": "https://scrapethissite.com/lessons/", "appearences": 0}
{"link": "https://scrapethissite.com/faq/", "appearences": 0}
{"link": "https://scrapethissite.com/login/", "appearences": 0}
{"link": "https://www.iana.org/domains/example", "appearences": 1}
{"link": "https://scrapethissite.com/pages/", "appearences": 0}
{"link": "https://scrapethissite.com/pages/simple/", "appearences": 0}
{"link": "https://scrapethissite.com/pages/forms/", "appearences": 0}
{"link": "https://scrapethissite.com/pages/ajax-javascript/", "appearences": 0}
{"link": "https://scrapethissite.com/pages/frames/", "appearences": 0}
{"link": "https://scrapethissite.com/pages/advanced/", "appearences": 0}
{"link": "https://scrapethissite.com/lessons/", "appearences": 0}
{"link": "https://gum.co/oLpqb?wanted=true", "appearences": 2}
{"link": "https://gum.co/oLpqb/LASTCHANCE?wanted=true", "appearences": 2}
{"link": "https://scrapethissite.com/faq/", "appearences": 0}
{"link": "https://scrapethissite.com/robots.txt", "appearences": 0}
{"link": "https://scrapethissite.com/login/", "appearences": 0}
{"link": "https://www.iana.org/", "appearences": 0}
